project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false
  render:
    - processing_flow_stac.ipynb

website:
  title: "Gapless S2 index mosaics"
  navbar:
    background: primary
    left:
      - href: processing_flow_stac.ipynb
        text: Processing flow with Paituli STAC

format:
  html:
    theme: syke.scss
    toc: true