name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: check out repo
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false

      - name: Generate README.md
        run: quarto render README.ipynb

      - name: stage README.md
        run: git add README.md
      
      - name: commit README.md
        run: git commit -m 'Auto-updating README.md'

      - name: fetch from main
        run: git fetch origin main

      - name: push to main
        run: git push origin HEAD:main

      - name: create docs
        run: quarto render --output-dir _docs

      - name: deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          force_orphan: true
          publish_dir: ./_docs
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com